// Copyright 2018 Hajime Hoshi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

'use strict';

(async () => {
    let readStdin = async () => {
        const chunks = [];
        let length = 0;

        await new Promise((resolve, reject) => {
            const stdin = process.stdin;
            stdin.on('data', (chunk) => {
                chunks.push(chunk);
                length += chunk.length;
            });
            stdin.on('end', () => {
                resolve();
            });
            stdin.on('error', (error) => {
                reject(error);
            });
        });

        return Buffer.concat(chunks, length);
    }

    let bin = await readStdin();

    console.log(`// Code generated by genpre.go. DO NOT EDIT.`);
    console.log(``);
    console.log(`var stbvorbis = typeof stbvorbis !== 'undefined' ? stbvorbis : {};`);
    console.log(`(function() { // Begin of the scope.`);
    console.log(`function decodeWorker() { // Begin of function decodeWorker().`);
    console.log(`var Module = typeof Module !== 'undefined' ? Module : {};`);
    console.log(`var useWasm = true;`);
    console.log(`Module['wasmBinary'] = Uint8Array.from(atob('${bin.toString('base64')}'), function(c) { return c.charCodeAt(0); });`);
})();
